<a href="https://colab.research.google.com/github/kshiny/NumPy/blob/main/NumPy21-25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ✅ Solving the questions 21, 22, 24, 25 again.

---

In [1]:
import numpy as np

### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

* np.tile(arr, reps) : 배열을 반복하면서 새로운 축을 추가하기

In [7]:
a = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 22. Normalize a 5x5 random matrix (★☆☆)


* 변수들 간의 척도가 서로 다른 경우 직접적으로 상호 비교를 할 수가 없다.
    * 모델링 작업에 들어가기 전에 변수들 간의 척도가 다른 경우 보통 표준화를 진행한다.
* NumPy를 이용한 표준화 : z = (x-mean())/std()

In [11]:
a = np.random.random((5,5))
a = (a-np.mean(a)) / (np.std(a))
print(a)

[[ 0.80619947 -2.23706714 -0.59777222 -0.57729837 -0.9329623 ]
 [ 0.35283253 -0.80939086  0.77874083 -0.30035233  0.93686203]
 [-0.11414231 -1.94121809 -1.10400553  1.48993695  0.52263795]
 [ 0.33462127  0.51723817  0.8487995   1.14435506  1.17660042]
 [-1.67102657  0.47745922  0.59801794 -0.4496291   0.75056349]]


### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [13]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

* np.dot은 numpy array를 곱할 때 사용한다.

In [14]:
a = np.dot(np.ones((5,3)), np.ones((3,2)))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [17]:
a = np.arange(11)
a[(3<a) & (a<8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
