<a href="https://colab.research.google.com/github/kshiny/Numpy/blob/main/Numpy_%7C_1~10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ✅ Solving the questions 2, 4, 5, 8, 9, 10 again.

---



### 1. Import the numpy package under the name np (★☆☆)

In [2]:
import numpy as np

### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.show_config()

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [4]:
np.version.version

'1.19.5'

In [5]:
# numexpr은 numpy array의 단순 연산의 성능을 높여주는 evaluator라고 한다.
import numexpr
numexpr.print_versions()

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Numexpr version:   2.7.3
NumPy version:     1.19.5
Python version:    3.7.12 (default, Sep 10 2021, 00:21:48) 
[GCC 7.5.0]
Platform:          linux-x86_64-#1 SMP Tue Dec 7 09:58:10 PST 2021
CPU vendor:        
CPU model:         
CPU clock speed:    MHz
VML available?     False
Number of threads used by default: 2 (out of 2 detected cores)
Maximum number of threads: 64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


### 3. Create a null vector of size 10 (★☆☆)

* null vector는 영벡터를 의미한다.



In [6]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. How to find the memory size of any array (★☆☆)

* numpy.itemsize : 배열 각 멤버의 바이트 크기를 리턴

In [7]:
a = np.zeros((10, 10))
print(a.nbytes)
print("%d bytes" % (a.size * a.itemsize))

800
800 bytes


### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

* numpy의 add function에 대한 설명 문서를 불러오는 방법

In [8]:
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
a = np.arange(10, 50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 8. Reverse a vector (first element becomes last) (★☆☆)

* arr[::2] : 처음부터 끝까지 두 칸 간격으로
* arr[1::2] : 1부터 끝까지 두 칸 간격으로
* arr[::-1] : 처음부터 끝까지 역순
* arr[::-2] : 처음부터 끝까지 두 칸 간격으로 역순
* arr[3::-1] : 3부터 끝까지 역순

In [11]:
a = np.arange(50)
a[::-1]
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


### 9. Create a 3x3 matrix with values ranging from from 0 to 8 (★☆☆)

In [12]:
a = np.arange(9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)
