## ✅ Solving the questions 15, 16, 18, 19, 20 again.

---

In [2]:
import numpy as np

### 11. Create a 3x3 identity matrix (★☆☆)

* 선형대수학에서, 단위 행렬(unit matrix) 또는 항등 행렬(identity matrix)은 주대각선의 원소가 모두 1이며 나머지 원소는 모두 0인 정사각 행렬이다.
* np.eye() : 단위행렬 생성

In [3]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 12. Create a 3x3x3 array with random values (★☆☆)

* np.random.rand() : 0~1 사이의 값의 uniform distribution 균일 분포, 균등 분포라고 불리는 값을 return 하는 함수이다.
* np.random.randn() : Normal(Gaussian) Distribution 정규 분포, 가우시안 분포라고 불리는 값을 return 하는 함수이다. 대체로 -1~1 사이의 값을 얻는다.
* numpy.random.randint : 정수 값만을 return 하는 함수이다.
* numpy.random.random : 앞의 np.random.rand와 비슷한 형태로, 다른 점은 1에서 설명한 것은 0~1 사이이지만 여기서는 0~1보다 작은 값의 범주라는 것이다.


In [4]:
a = np.random.random((3,3,3))
print(a)

[[[0.72391861 0.99581624 0.3699219 ]
  [0.06071824 0.68216684 0.9214064 ]
  [0.81209836 0.05267265 0.19476124]]

 [[0.77628987 0.79543112 0.71434767]
  [0.22370147 0.58362045 0.42540812]
  [0.26528494 0.44866384 0.2503628 ]]

 [[0.04824435 0.86479481 0.06761276]
  [0.17869232 0.61691762 0.83878104]
  [0.24650087 0.87690933 0.61289584]]]


### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [5]:
a = np.random.random((10, 10))
print(a)
amin, amax = a.min(), a.max()
print(amin, amax)

[[0.00601844 0.95230693 0.46261641 0.0057961  0.3284472  0.91065522
  0.34072436 0.06102944 0.71657397 0.06085212]
 [0.18229927 0.66524894 0.49159615 0.00961391 0.70040899 0.36282981
  0.24027482 0.18643571 0.52922237 0.86804682]
 [0.5151428  0.95797231 0.09160675 0.17041426 0.27224489 0.22024228
  0.47151242 0.50317004 0.19407148 0.07851593]
 [0.70580759 0.10670928 0.59010323 0.1679032  0.15085938 0.19672374
  0.78188615 0.52236558 0.68300509 0.26854296]
 [0.31381212 0.90851331 0.39469075 0.36379182 0.24735614 0.7536487
  0.97584938 0.12599734 0.24441807 0.88802013]
 [0.52314253 0.61918139 0.31262377 0.77909851 0.814089   0.7591442
  0.55642489 0.37841564 0.45520685 0.68579988]
 [0.24532033 0.06273532 0.92172583 0.45823468 0.59548371 0.18847216
  0.49281447 0.9873459  0.75831271 0.51792747]
 [0.84438448 0.87980263 0.06640663 0.70048814 0.51500977 0.45741933
  0.07183022 0.86812516 0.25435606 0.67949742]
 [0.95645258 0.70192326 0.86580779 0.36449966 0.86955696 0.45424544
  0.33930964 0

### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [6]:
a = np.random.random(30)
m = a.mean()
print(m)

0.5678438027278451


### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [7]:
a = np.ones((10, 10))
a[1:-1, 1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

* np.pad() 함수를 사용하여 배열(array)을 특정 형상의 배열로 변형할 때 빈자리를 '0'으로 채우기
* np.pad(array, pad_width, mode='constant', **kwargs)
* pad_width : 위의 행 1개, 왼쪽 열 1개 추가, 아래 행 1개 추가, 오른쪽 열 1개 추가
* constant_values : '0' 대신에 원하는 다른 특정 상수 값으로 빈 자리를 채워넣을 수 있다.

In [8]:
a = np.ones((5, 5))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


### 17. What is the result of the following expression? (★☆☆)

* nan은 '정의되지 않은 수'이기 때문에 비교하거나 연산할 수 없다.
* np.nan은 np.nan의 집합 내에 속한다.
* 3 * 0.1 = 0.300000000004로 출력된다. 부동소수점에 의한 오차를 나타낸다.

In [9]:
0 * np.nan # nan
np.nan == np.nan # False
np.inf > np.nan # False
np.nan - np.nan # nan
np.nan in set([np.nan]) # True
0.3 == 3 * 0.1 #False

False

### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

* np.diag()은 주어진 원소로 대각행렬을 만들어 준다. k를 기준으로 대각선 아래/위에 삽입 가능

In [16]:
a = np.diag(1+np.arange(4), k=-1) # np.arage(4) : 0부터 3까지이기 때문에 1을 더함
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [18]:
a = np.diag([1,2,3,4], k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [26]:
a = np.zeros((8,8))
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
* np.unravel_index : 플랫 인덱스 또는 플랫 인덱스 배열을 튜플 좌표 배열로 변환한다.

In [28]:
a = np.unravel_index(99, (6,7,8))
print(a)

(1, 5, 3)
